services:
  discordmusicbot.runner:
    image: ${DOCKER_REGISTRY-}discordmusicbotrunner
    build:
      context: .
      dockerfile: DiscordMusicBot.Runner/Dockerfile
    volumes:
      - ./DiscordMusicBot.Runner/appsettings.json:/app/resources/appsettings.json